#!/bin/sh -x
#
# run this from the src/ directory!

SRCDIR=`pwd`
# the following are paths relative to the source dir ${SRCDIR}
DOWNLOADS="../downloads"
BUILDTOOLS="buildtools"

# determine version number
VERSION=`grep VERSION=\" dobuild | cut -d\" -f2`
SHORTNAME=`grep SHORTNAME=\" dobuild | cut -d\" -f2`
USCORED_VERSION=`echo $VERSION | tr . _`
CAPS_SHORTNAME=`echo ${SHORTNAME} | tr a-z A-Z`
RELEASE_TAG="${CAPS_SHORTNAME}_${USCORED_VERSION}"


# create new version directory

if [ ! -d ${DOWNLOADS}/${VERSION} ]; then
	mkdir ${DOWNLOADS}/${VERSION}
fi

# dobuild
./dobuild suite && ./dobuild tbird && ./dobuild suiterunner
#or quit...

for target in tbird suite suiterunner; do
	cp build/${target}/${SHORTNAME}_${target}.xpi ${DOWNLOADS}/${VERSION}/${SHORTNAME}_${VERSION}_${target}.xpi 
	cp build/${target}/${SHORTNAME}_${target}.xpi ${DOWNLOADS}/latest/
done
	
cvs -d :pserver:eyalroz@mozdev.org:/cvs tag ${RELEASE_TAG}

cd ${SRCDIR}/${BUILDTOOLS}

cvs -d :pserver:eyalroz@mozdev.org:/cvs tag ${RELEASE_TAG}

cd ${SRCDIR}/${DOWNLOADS}

cvs -d :pserver:eyalroz@mozdev.org:/cvs add ${VERSION}/ 
cvs -d :pserver:eyalroz@mozdev.org:/cvs add `ls ${VERSION}/*.xpi`
cvs -d :pserver:eyalroz@mozdev.org:/cvs ci ${VERSION}/ latest/

