#!/bin/sh -x
#
# run this from the src/ directory!

DOWNLOADS="../downloads"
BUILDTOOLS="buildtools"

# determine version number
VERSION=`grep VERSION=\" dobuild | cut -d\" -f2`
SHORTNAME=`grep SHORTNAME=\" dobuild | cut -d\" -f2`
USCORED_VERSION=`echo $VERSION | tr . _`
CAPS_SHORTNAME=`echo ${SHORTNAME} | tr a-z A-Z`
RELEASE_TAG="${CAPS_SHORTNAME}_${USCORED_VERSION}"


# create new version directory

if [ ! -d ${DOWNLOADS}/${VERSION} ]; then
	mkdir ${DOWNLOADS}/${VERSION}
fi

# dobuild
./dobuild suite && ./dobuild tbird && ./dobuild suiterunner
#or quit...

for target in tbird suite suiterunner; do
	cp build/tbird/${SHORTNAME}_${target}.xpi ${DOWNLOADS}/${VERSION}/${SHORTNAME}_${VERSION}_${target}.xpi 
	cp build/tbird/${SHORTNAME}_${target}.xpi ${DOWNLOADS}/latest/
done
	
#cp build/tbird/${SHORTNAME}_tbird.xpi build/suite/${SHORTNAME}_suite.xpi build/suiterunner/${SHORTNAME}_suiterunner.xpi ${DOWNLOADS}/${VERSION}/ 
#cp -f build/tbird/${SHORTNAME}_tbird.xpi build/suite/${SHORTNAME}_suite.xpi build/suiterunner/${SHORTNAME}_suiterunner.xpi ${DOWNLOADS}/latest/

cvs -d :pserver:eyalroz@mozdev.org/cvs tag  ${RELEASE_TAG}

cd ${BUILDTOOLS}

cvs -d :pserver:eyalroz@mozdev.org/cvs tag  ${RELEASE_TAG}

cd ${DOWNLOADS}
cvs -d :pserver:eyalroz@mozdev.org/cvs add ${VERSION}/ 
cvs -d :pserver:eyalroz@mozdev.org/cvs add ${VERSION}/${SHORTNAME}_tbird.xpi ${VERSION}/${SHORTNAME}_suite.xpi ${VERSION}/${SHORTNAME}_suiterunner.xpi
cvs -d :pserver:eyalroz@mozdev.org/cvs ci

